import argparse
import json
from pathlib import Path

from experiment_pipeline import load_scores, make_predictions, read_json, write_jsonl
from mapping_evaluator import QAMappingEvaluator


def main():
    parser = argparse.ArgumentParser(description="Evaluate the validation winner on the held-out test split.")
    parser.add_argument("--validation-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, help="Defaults to the path recorded by validation")
    args = parser.parse_args()

    winner_path = args.validation_dir / "frozen_winner.json"
    config = read_json(winner_path)
    if config.get("selected_by") != "validation ranking":
        raise ValueError(f"{winner_path} was not generated by the validation runner")
    with (args.validation_dir / "summary.jsonl").open("r", encoding="utf-8") as file:
        ranked_validation = [json.loads(line) for line in file if line.strip()]
    if not ranked_validation:
        raise ValueError(f"No ranked validation results found in {args.validation_dir}")
    best_validation = ranked_validation[0]
    winner = config["winner"]
    identity_fields = ("representation", "method", "top_k", "threshold", "margin")
    if any(best_validation.get(key) != winner.get(key) for key in identity_fields):
        raise ValueError("Frozen winner does not match the top-ranked validation configuration")

    test_ids = read_json(config["split_ids_path"])
    files = {key: Path(value) for key, value in config["representation_artifacts"].items()}
    test_scores, chunk_ids = load_scores(files, test_ids, "winner")
    predictions = make_predictions(winner, test_scores, chunk_ids, test_ids)
    evaluator = QAMappingEvaluator(config["gold_path"])
    result = evaluator.eval(
        predictions,
        question_ids=test_ids,
    )

    output_dir = args.output_dir or Path(config["test_output_dir"])
    output_dir.mkdir(parents=True, exist_ok=False)
    manifest = {
        "split": "test",
        "winner_config_path": str(winner_path),
        "validation_run_dir": config["validation_run_dir"],
        "validation_metrics": config["validation_metrics"],
        "gold_path": config["gold_path"],
        "split_ids_path": config["split_ids_path"],
        "winner": winner,
        "representation_artifacts": {key: str(path) for key, path in files.items()},
    }
    (output_dir / "run_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    name_parts = [winner["representation"], winner["method"]]
    for key in ("top_k", "threshold", "margin"):
        if key in winner:
            name_parts.append(f"{key}_{winner[key]}")
    name = "_".join(name_parts)
    write_jsonl(output_dir / f"{name}_predictions.jsonl", predictions)
    with (output_dir / f"{name}_evaluation.json").open("w", encoding="utf-8") as file:
        json.dump({"experiment": winner, "split": "test", **result}, file, ensure_ascii=False, indent=2)
    summary = {"experiment": name, **winner, **result["summary"]}
    with (output_dir / "summary.jsonl").open("w", encoding="utf-8") as file:
        file.write(json.dumps(summary, ensure_ascii=False) + "\n")
    print(
        f"{name}: F1={summary['mean_question_f1']:.4f}, "
        f"exact={summary['exact_match_rate']:.4f}, "
        f"precision={summary['mean_question_precision']:.4f}, "
        f"avg_chunks={summary['average_selected_chunks']:.2f}"
    )
    print(f"Run saved to: {output_dir}")


if __name__ == "__main__":
    main()
